### PR TITLE
fixes #1880 pagination not work

### LINKED ISSUE #1880: portal编辑灰度规则，通过cgi获取ip列表时，分页功能失效
接口是：portal的`/envs/PRO/instances/by-namespace`
版本： 1.1.0
这里有参数 `page` 和 `size`，   我试了一下， 无论怎么改， 都是返回全部内容，没有达到分页效果。

### PR DESCRIPTION
**Pull request by kezhenxu94**
Fixes #1880

### CODE REVIEW

File: apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/repository/InstanceConfigRepositoryTest.java [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+ *
+ * @author kezhenxu94 (kezhenxu94 at 163 dot com)
+ */
+public class InstanceConfigRepositoryTest extends AbstractIntegrationTest {
+  @Autowired
+  private InstanceConfigRepository instanceConfigRepository;
+  @Autowired
+  private InstanceRepository instanceRepository;
+
+  @Test
```
Comment (nobodyiam) [inline apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/repository/InstanceConfigRepositoryTest.java]: annotated with `@Rollback`?

Comment (kezhenxu94) [reply apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/repository/InstanceConfigRepositoryTest.java]: done
