### PR TITLE
Try to support JDK 8+

### LINKED ISSUE #2073: jdk1.8可以启动，但是相同配置换成jdk9，jdk11，jdk12都无法启动
[root@bogon scripts]# ./startup.sh 
2019年 03月 23日 星期六 00:26:11 CST ==== Starting ==== 
Started [5636]
Waiting for server startup.
pid - 5636 just quit unexpectedly, please check logs under /opt/logs/100003171 and /tmp for more information!

apollo的配置都没问题，但是jdk切到9,11,12都如上报错，换成jdk8就可用，想问下怎么解决在高jdk下使用？

### PR DESCRIPTION
**Pull request by kezhenxu94**
- [x] Make it run under Java 8, Java 9, Java 10(untested), Java 11
- [x] Test under Java 10
- [x] Convert incompatible JVM arguments under Java 8 to Java 9, 10, 11 respectively(and perhaps 12)

resolve #2073

### CODE REVIEW

File: apollo-adminservice/src/main/scripts/startup.sh [hunk 1]
```diff
@@ -53,6 +56,35 @@ if [ "$windows" == "1" ] && [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java"
...
+if [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
+    _java="$JAVA_HOME/bin/java"
+else
+    echo "no executable java command found"
+    exit 1
+fi
+
+if [[ "$_java" ]]; then
+    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
+    echo version "$version"
```
Comment (nobodyiam) [inline apollo-adminservice/src/main/scripts/startup.sh]: Is it necessary to print out `version 1.8.0_60` and `java version >= 8` as they look more like debug messages?

File: apollo-adminservice/src/main/scripts/startup.sh [hunk 2]
```diff
@@ -53,6 +56,35 @@ if [ "$windows" == "1" ] && [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java"
...
+    version=$(echo "$version" | awk -F. '{printf("%03d%03d",$1,$2);}')
+    # now version is of format 009003 (9.3.x)
+    if [ $version -ge 011000 ]; then
+        echo "java version >= 11"
+        JAVA_OPTS="$JAVA_OPTS -Xlog:gc*:$LOG_DIR/gc.log -Xlog:safepoint -Xlog:gc+heap=trace"
```
Comment (nobodyiam) [inline apollo-adminservice/src/main/scripts/startup.sh]: is there any equivalent set up for `-XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=5M` in jdk 9+?

File: apollo-adminservice/src/main/scripts/startup.sh [hunk 3]
```diff
@@ -53,6 +56,35 @@ if [ "$windows" == "1" ] && [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java"
     echo "Windows new JAVA_HOME is: $JAVA_HOME"
 fi
 
+if [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
```
Comment (nobodyiam) [inline apollo-adminservice/src/main/scripts/startup.sh]: the logic for spring boot to locate java is as follows, shall we reuse the logic?

```bash
# Find Java
if [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]]; then
    javaexe="$JAVA_HOME/bin/java"
elif type -p java > /dev/null 2>&1; then
    javaexe=$(type -p java)
elif [[ -x "/usr/bin/java" ]];  then
    javaexe="/usr/bin/java"
else
    echo "Unable to find Java"
    exit 1
fi
```

**Comment by nobodyiam** [comment]
there are also some startup scripts under apollo-on-kubernetes folder, e.g. [startup-kubernetes.sh](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-kubernetes/apollo-config-server/scripts/startup-kubernetes.sh), maybe we also modify them?

File: apollo-adminservice/src/main/scripts/startup.sh (hunk 2 above)
Comment (kezhenxu94) [reply apollo-adminservice/src/main/scripts/startup.sh]: Here is the documentation that I referred to do the migration, it says **Log rotation is handled by the framework.** and I assumed that it's enable by default, am I right?

image

[here](https://docs.oracle.com/javase/9/tools/java.htm#JSWOR-GUID-31503FCE-93D0-4175-9B4F-F6A738B2F4C4) is the documentation

File: apollo-adminservice/src/main/scripts/startup.sh (hunk 1 above)
Comment (kezhenxu94) [reply apollo-adminservice/src/main/scripts/startup.sh]: Good catch! I'll remove them and only leave necessary messages

**Comment by kezhenxu94** [comment]
> there are also some startup scripts under apollo-on-kubernetes folder, e.g. [startup-kubernetes.sh](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-kubernetes/apollo-config-server/scripts/startup-kubernetes.sh), maybe we also modify them?

updated

**Comment by nobodyiam** [comment]
> > there are also some startup scripts under apollo-on-kubernetes folder, e.g. [startup-kubernetes.sh](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-kubernetes/apollo-config-server/scripts/startup-kubernetes.sh), maybe we also modify them?
> 
> updated

looks like `scripts/apollo-on-kubernetes/apollo-admin-server/scripts/startup-kubernetes.sh` is different from others?

File: apollo-adminservice/src/main/scripts/startup.sh [hunk 4]
```diff
@@ -53,6 +56,35 @@ if [ "$windows" == "1" ] && [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java"
...
+if [[ "$javaexe" ]]; then
+    version=$("$javaexe" -version 2>&1 | awk -F '"' '/version/ {print $2}')
+    version=$(echo "$version" | awk -F. '{printf("%03d%03d",$1,$2);}')
+    # now version is of format 009003 (9.3.x)
+    if [ $version -ge 011000 ]; then
+        JAVA_OPTS="$JAVA_OPTS -Xlog:gc*:$LOG_DIR/gc.log -Xlog:safepoint -Xlog:gc+heap=trace"
+    elif [ $version -ge 010000 ]; then
+        JAVA_OPTS="$JAVA_OPTS -Xlog:gc*:$LOG_DIR/gc.log -Xlog:safepoint -Xlog:gc+heap=trace"
+    elif [ $version -ge 009000 ]; then
+        JAVA_OPTS="$JAVA_OPTS -Xlog:gc*:$LOG_DIR/gc.log -Xlog:safepoint -Xlog:gc+heap=trace"
```
Comment (nobodyiam) [inline apollo-adminservice/src/main/scripts/startup.sh]: It's better to print out the `Current time and date`([2019-04-06T20:48:47.390-0800]) instead of `Time since the start of the JVM in seconds and milliseconds.`([0.444s]). So it's better to decorate the gc output like `-Xlog:gc*:$LOG_DIR/gc.log:time,level,tags`. See [Decorations](https://docs.oracle.com/javase/9/tools/java.htm#JSWOR-GUID-BE93ABDC-999C-4CB5-A88B-1994AAAC74D5#GUID-BE93ABDC-999C-4CB5-A88B-1994AAAC74D5__DECORATIONS-A7A4AD31)
