### PR TITLE
fix apollo config data loader with profiles

### LINKED ISSUE #3867: apollo client config data start failed with spring.profiles.active
**Describe the bug**
Spring Boot start with active profile failed
```
02:39:53.896 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.boot.context.config.InvalidConfigDataPropertyException: Property 'spring.profiles.active' imported from location 'ApolloConfigDataResource{namespace='application'}' is invalid in a profile specific resource [origin: "spring.profiles.active" from property source "application"]
	at org.springframework.boot.context.config.InvalidConfigDataPropertyException.lambda$throwOrWarn$1(InvalidConfigDataPropertyException.java:125)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
	at org.springframework.boot.context.config.InvalidConfigDataPropertyException.throwOrWarn(InvalidConfigDataPropertyException.java:122)
	at org.springframework.boot.context.config.ConfigDataEnvironment.checkForInvalidProperties(ConfigDataEnvironment.java:361)
	at org.springframework.boot.context.config.ConfigDataEnvironment.applyToEnvironment(ConfigDataEnvironment.java:325)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:233)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:86)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:375)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318)
```

**To Reproduce**
1. start with `-Dspring.profiles.active=xxx`

@klboke

### PR DESCRIPTION
**Pull request by vdisk-group**
## What's the purpose of this PR

fix apollo config data loader with profiles

## Which issue(s) this PR fixes:
Fixes #3867

## Brief changelog

add a field `m_pureApolloConfig` for `DefaultConfig` to prevent the `DefaultConfig` return the properties from the `system property` or `environment variables` when work with config data loader.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [x] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by nobodyiam** [comment]
Is it possible to write a test case to show what this pr solves?

**Comment by lonre** [comment]
Hi @vdisk-group 

Is it possible that we make an alternative implement for `DefaultConfig`?

That would seems much clear

**Comment by vdisk-group** [comment]
> Is it possible to write a test case to show what this pr solves?

add a test

**Comment by vdisk-group** [comment]
> Hi @vdisk-group
> 
> Is it possible that we make an alternative implement for `DefaultConfig`?
> 
> That would seems much clear

add a base class `AbstractRepositoryConfig` and an alternative implement `PureApolloConfig`

**Comment by lonre** [comment]
In the mean time, I have been thinking about a question that if we can omit `m_pureApolloConfig`?

Can we detect the running environment? if the client is used with apollo config data loader, then use `PureApolloConfig`, else use `DefaultConfig`

@vdisk-group

**Comment by vdisk-group** [comment]
> In the mean time, I have been thinking about a question that if we can omit `m_pureApolloConfig`?
> 
> Can we detect the running environment? if the client is used with apollo config data loader, then use `PureApolloConfig`, else use `DefaultConfig`
> 
> @vdisk-group

remove the `m_pureApolloConfig` and use spi to decide whether to use `PureApolloConfig` or `DefaultConfig`

File: apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+      value = this.getPropertyFromAdditional(key);
+    }
+
+    this.tryWarnLog(value);
+
+    return value == null ? defaultValue : value;
+  }
+
+  @Override
+  public Set<String> getPropertyNames() {
```
Comment (nobodyiam) [inline apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java:56]: Is it necessary to also update the getPropertyNames logic of DefaultConfig?

File: apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+
+import com.ctrip.framework.apollo.util.ApolloHashMapInitialUtil;
+import java.util.HashSet;
+import java.util.Set;
+import org.springframework.util.CollectionUtils;
+
+/**
+ * @author vdisk <vdisk@foxmail.com>
+ */
+public class PureApolloConfig extends AbstractRepositoryConfig implements RepositoryChangeListener {
```
Comment (nobodyiam) [inline apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java:27]: Is it better to move this file to `apollo-client-data-config` module?

File: apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+   * @param namespace        the namespace of this config instance
+   * @param configRepository the config repository for this config instance
+   */
+  public PureApolloConfig(String namespace,
+      ConfigRepository configRepository) {
+    super(namespace, configRepository);
+  }
+
+  @Override
+  public String getProperty(String key, String defaultValue) {
```
Comment (nobodyiam) [inline apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java:41]: It looks like the only difference between PureApolloConfig and DefaultConfig is the getProperty method, then is it simpler to let PureApolloConfig extends DefaultConfig and override the getProperty method?

File: apollo-client/src/main/java/com/ctrip/framework/apollo/spi/DefaultConfigFactory.java [hunk 4]
```diff
@@ -43,19 +44,21 @@
...
     m_configUtil = ApolloInjector.getInstance(ConfigUtil.class);
+    m_repositoryConfigFactory = ApolloInjector.getInstance(RepositoryConfigFactory.class);
   }
 
   @Override
   public Config create(String namespace) {
     ConfigFileFormat format = determineFileFormat(namespace);
     if (ConfigFileFormat.isPropertiesCompatible(format)) {
-      return new DefaultConfig(namespace, createPropertiesCompatibleFileConfigRepository(namespace, format));
+      return this.m_repositoryConfigFactory.createConfig(namespace, createPropertiesCompatibleFileConfigRepository(namespace, format));
```
Comment (nobodyiam) [inline apollo-client/src/main/java/com/ctrip/framework/apollo/spi/DefaultConfigFactory.java:59]: I'm not sure whether it's necessary to add another abstraction of RepositoryConfigFactory. Is it simpler to write a custom config factory in `apollo-client-config-data` module which extends DefaultConfigFactory and only overrides the `create` method, then we could use the ApolloConfigDataInjectorCustomizer to customize the injector?

**Review by nobodyiam — CHANGES_REQUESTED** [review]

File: apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java (hunk 1 above)
Comment (vdisk-group) [reply apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java]: updated

File: apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java (hunk 2 above)
Comment (vdisk-group) [reply apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java]: moved

File: apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java (hunk 3 above)
Comment (vdisk-group) [reply apollo-client/src/main/java/com/ctrip/framework/apollo/internals/PureApolloConfig.java]: resolved

File: apollo-client/src/main/java/com/ctrip/framework/apollo/spi/DefaultConfigFactory.java (hunk 4 above)
Comment (vdisk-group) [reply apollo-client/src/main/java/com/ctrip/framework/apollo/spi/DefaultConfigFactory.java]: resolved

File: apollo-client/src/main/java/com/ctrip/framework/apollo/internals/AbstractRepositoryConfig.java [hunk 5]
```diff
@@ -0,0 +1,278 @@
...
+import java.util.Properties;
+import java.util.Set;
+import java.util.concurrent.atomic.AtomicReference;
+import org.slf4j.Logger;
+
+
+/**
+ * @author Jason Song(song_s@ctrip.com)
+ */
+public abstract class AbstractRepositoryConfig extends AbstractConfig implements
```
Comment (nobodyiam) [inline apollo-client/src/main/java/com/ctrip/framework/apollo/internals/AbstractRepositoryConfig.java:44]: It looks like we could move the logic back to DefaultConfig?

File: apollo-client/src/main/java/com/ctrip/framework/apollo/util/ApolloHashMapInitialUtil.java [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+ */
+public class ApolloHashMapInitialUtil {
+
+  /**
+   * calculate initial capacity of hash map {@link java.util.HashSet#HashSet(java.util.Collection)}
+   *
+   * @param expectCapacity expect capacity
+   * @return initial capacity
+   */
+  public static int getInitialCapacity(int expectCapacity) {
```
Comment (nobodyiam) [inline apollo-client/src/main/java/com/ctrip/framework/apollo/util/ApolloHashMapInitialUtil.java:30]: Is it ok to use com.google.common.collect.Sets#newLinkedHashSetWithExpectedSize so that we don't need to maintain this logic in apollo?

File: apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfig.java [hunk 7]
```diff
@@ -103,151 +56,28 @@ public String getProperty(String key, String defaultValue) {
...
-        try {
-          in.close();
-        } catch (IOException ex) {
-          // ignore
-        }
-      }
-    }
-
-    return properties;
+    Set<String> fromRepository = this.getPropertyNamesFromRepository();
```
Comment (nobodyiam) [inline apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfig.java:70]: How about we only include propertyNamesFromRepository and propertyNamesFromAdditional? I have a little concern that if system property and system env are included, that might cause some compatibility issues, though this looks like the correct implementation.

Comment (vdisk-group) [reply apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfig.java:187]: resolved

File: apollo-client/src/main/java/com/ctrip/framework/apollo/util/ApolloHashMapInitialUtil.java (hunk 6 above)
Comment (vdisk-group) [reply apollo-client/src/main/java/com/ctrip/framework/apollo/util/ApolloHashMapInitialUtil.java]: remove the ApolloHashMapInitialUtil

File: apollo-client/src/main/java/com/ctrip/framework/apollo/internals/AbstractRepositoryConfig.java (hunk 5 above)
Comment (vdisk-group) [reply apollo-client/src/main/java/com/ctrip/framework/apollo/internals/AbstractRepositoryConfig.java]: remove the AbstractRepositoryConfig

File: apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfig.java [hunk 8]
```diff
@@ -103,37 +172,41 @@ public String getProperty(String key, String defaultValue) {
...
+    return propertyNames;
   }
 
   @Override
   public ConfigSourceType getSourceType() {
     return m_sourceType;
   }
 
-  private Set<String> stringPropertyNames(Properties properties) {
+  protected Set<String> stringPropertyNames(Properties properties) {
```
Comment (nobodyiam) [inline apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfig.java:207]: It seems it could still be private?
```suggestion
  private Set<String> stringPropertyNames(Properties properties) {
```

**Review by nobodyiam — APPROVED** [review]
LGTM
